
services:
#  app-music:
#    build: .
#    env_file:
#      - .env
#    ports:
#      - ${APP_PORT_MUSIC}:${APP_PORT_MUSIC}
#
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${DB_PORT_MUSIC}/${DB_NAME_MUSIC}
#      DB_USER_MUSIC: ${DB_USER_MUSIC}
#      DB_PASSWORD_MUSIC: ${DB_PASSWORD_MUSIC}
#      DB_NAME_MUSIC: ${DB_NAME_MUSIC}
#      DB_HOST_MUSIC: ${DB_HOST_MUSIC}
#      DB_PORT_MUSIC: ${DB_PORT_MUSIC}
#      DB_DDL_AUTO_MUSIC: ${DB_DDL_AUTO_MUSIC}
#      DB_DRIVER_MUSIC: ${DB_DRIVER_MUSIC}
#
#      SPRING_DATASOURCE_URL_MUSIC: ${SPRING_DATASOURCE_URL_MUSIC}
#      SPRING_DATASOURCE_USERNAME_MUSIC: ${SPRING_DATASOURCE_USERNAME_MUSIC}
#      SHOW_SQL_MUSIC: ${SHOW_SQL_MUSIC}
#
#      APP_PORT_MUSIC: ${APP_PORT_MUSIC}
#
#      JWT_SECRET_MUSIC: ${JWT_SECRET_MUSIC}
#      JWT_EXPIRATION_MUSIC: ${JWT_EXPIRATION_MUSIC}
#      JWT_REFRESH_EXPIRATION_MUSIC: ${JWT_REFRESH_EXPIRATION_MUSIC}
#      SEED_PASSWORD_ADMIN_MUSIC: ${SEED_PASSWORD_ADMIN_MUSIC}
#      SEED_EMAIL_ADMIN_MUSIC: ${SEED_EMAIL_ADMIN_MUSIC}
#      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
#      COOKIES_SECURE_MUSIC: true
#      SAME_SITE_MUSIC: None
#    networks:
#      - network-app-music

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - data-minio:/data
    networks:
      - network-app-music
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-buckets:
    image: quay.io/minio/mc:latest
    container_name: minio-buckets
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - network-app-music
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb --ignore-existing local/${MINIO_BUCKET} &&
      mc anonymous set download local/${MINIO_BUCKET} &&
      exit 0;
      "
  postgres:
    image: postgres:15
    container_name: postgreSQL
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER_MUSIC}"
      POSTGRES_PASSWORD: "${DB_PASSWORD_MUSIC}"
      POSTGRES_DB: "${DB_NAME_MUSIC}"
    ports:
      - "${DB_PORT_MUSIC}:${DB_PORT_MUSIC}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER_MUSIC} -d ${DB_NAME_MUSIC}"]
      interval: 10s
      timeout: 5s
      retries: 5
    # opcional, mas Ãºtil para debug:
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - network-app-music
volumes:
  postgres_data:
  data-minio:
networks:
  network-app-music:
    driver: bridge