spring:
  application:
    name: Select Music
  datasource:
    url: jdbc:postgresql://${DB_HOST_MUSIC}:${DB_PORT_MUSIC}/${DB_NAME_MUSIC}
    username: "${DB_USER_MUSIC}"
    password: ${DB_PASSWORD_MUSIC}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
    ddl-auto: ${DB_DDL_AUTO_MUSIC}
    show-sql: ${SHOW_SQL_MUSIC}


  flyway:
    placeholders:
      admin.password: ${SEED_PASSWORD_ADMIN_MUSIC}
      admin.email: ${SEED_EMAIL_ADMIN_MUSIC}

    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public

  server:
    port: ${APP_PORT_MUSIC}
  api:
    jwt:
      secret: ${JWT_SECRET_MUSIC}
      expiration: ${JWT_EXPIRATION_MUSIC}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION_MUSIC}
      secure: ${COOKIES_SECURE_MUSIC}
      same-site: ${SAME_SITE_MUSIC}
  app:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
minio:
  url: ${MINIO_HOST_URL}
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket: ${MINIO_BUCKET}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

